// GENERATED by scripts/vendor-catalogs.mjs — do not edit by hand.
// Run `npm run vendor:catalogs` to regenerate.

import { describe, expect, it } from 'vitest';
import {
  CONSTELLATIONS,
  MESSIER,
  MILKY_WAY,
  STARS,
  STAR_TUPLES,
  type MessierType,
} from './index';

const ALLOWED_TYPES: MessierType[] = [
  'galaxy',
  'open_cluster',
  'globular_cluster',
  'planetary_nebula',
  'diffuse_nebula',
  'supernova_remnant',
  'other',
];

const inRaRange = (ra: number) => Number.isFinite(ra) && ra >= 0 && ra < 360;
const inDecRange = (dec: number) => Number.isFinite(dec) && dec >= -90 && dec <= 90;

describe('stars', () => {
  it('has a usable number of stars', () => {
    expect(STARS.length).toBeGreaterThan(3000);
    expect(STAR_TUPLES.length).toBe(STARS.length);
  });

  it('keeps every coordinate in range', () => {
    for (const s of STARS) {
      expect(inRaRange(s.ra), `ra out of range for HIP ${s.hip}: ${s.ra}`).toBe(true);
      expect(inDecRange(s.dec), `dec out of range for HIP ${s.hip}: ${s.dec}`).toBe(true);
    }
  });

  it('is sorted by magnitude ascending', () => {
    for (let i = 1; i < STARS.length; i++) {
      expect(STARS[i].mag).toBeGreaterThanOrEqual(STARS[i - 1].mag);
    }
  });

  it('has a finite B-V for every star', () => {
    for (const s of STARS) expect(Number.isFinite(s.bv)).toBe(true);
  });

  it('keeps the proper names a planetarium needs', () => {
    const byName = new Map(STARS.filter((s) => s.name).map((s) => [s.name, s]));
    for (const n of ['Vega', 'Sirius', 'Polaris', 'Betelgeuse', 'Rigel']) {
      expect(byName.has(n), `missing star name ${n}`).toBe(true);
    }
    // Sirius is the brightest star in the sky, so it must sort first.
    expect(STARS[0].name).toBe('Sirius');
  });
});

describe('constellations', () => {
  it('ships the full IAU set', () => {
    expect(CONSTELLATIONS.length).toBeGreaterThanOrEqual(88);
    expect(new Set(CONSTELLATIONS.map((c) => c.id)).size).toBe(CONSTELLATIONS.length);
  });

  it('keeps every coordinate in range', () => {
    for (const c of CONSTELLATIONS) {
      expect(inRaRange(c.labelRa), `label ra for ${c.id}`).toBe(true);
      expect(inDecRange(c.labelDec), `label dec for ${c.id}`).toBe(true);
      for (const line of c.lines) {
        for (const [ra, dec] of line) {
          expect(inRaRange(ra), `ra out of range in ${c.id}: ${ra}`).toBe(true);
          expect(inDecRange(dec), `dec out of range in ${c.id}: ${dec}`).toBe(true);
        }
      }
    }
  });

  it('never jumps across the sky between two consecutive points', () => {
    for (const c of CONSTELLATIONS) {
      for (const line of c.lines) {
        expect(line.length).toBeGreaterThanOrEqual(2);
        for (let i = 1; i < line.length; i++) {
          const jump = Math.abs(line[i][0] - line[i - 1][0]);
          expect(jump, `RA jump of ${jump} in ${c.id}`).toBeLessThanOrEqual(180);
        }
      }
    }
  });

  it('has a name and at least one label for every constellation', () => {
    for (const c of CONSTELLATIONS) {
      expect(c.name.length).toBeGreaterThan(0);
      expect(c.labels.length).toBeGreaterThanOrEqual(1);
      expect(c.labels[0]).toEqual([c.labelRa, c.labelDec]);
    }
    expect(CONSTELLATIONS.find((c) => c.id === 'Ori')?.name).toBe('Orion');
  });

  it('merges the two Serpens halves under the IAU name, keeping both labels', () => {
    const ser = CONSTELLATIONS.find((c) => c.id === 'Ser');
    expect(ser, 'Ser missing').toBeDefined();
    expect(ser!.name).toBe('Serpens');
    expect(ser!.labels.length).toBe(2);
    expect(ser!.lines.length).toBeGreaterThanOrEqual(2);
  });
});

describe('messier', () => {
  it('has exactly 110 objects, M1..M110', () => {
    expect(MESSIER.length).toBe(110);
    expect(MESSIER.map((o) => o.id)).toEqual(
      Array.from({ length: 110 }, (_, i) => `M${i + 1}`),
    );
  });

  it('only uses the allowed types', () => {
    for (const o of MESSIER) {
      expect(ALLOWED_TYPES, `${o.id} has type ${o.type}`).toContain(o.type);
    }
  });

  it('keeps every coordinate in range', () => {
    for (const o of MESSIER) {
      expect(inRaRange(o.ra), `ra out of range for ${o.id}: ${o.ra}`).toBe(true);
      expect(inDecRange(o.dec), `dec out of range for ${o.id}: ${o.dec}`).toBe(true);
    }
  });

  // J2000 positions from SIMBAD. M42 gets a wider tolerance because
  // d3-celestial's centroid for the Orion Nebula sits 3.6' south of the SIMBAD
  // position — inside a nebula 66' across. The other three pin the transform
  // to better than 0.01 deg.
  it('matches the golden coordinates', () => {
    const golden: Record<string, { ra: number; dec: number; tol: number }> = {
      M31: { ra: 10.685, dec: 41.269, tol: 0.05 },
      M42: { ra: 83.82, dec: -5.39, tol: 0.08 },
      M45: { ra: 56.75, dec: 24.12, tol: 0.05 },
      M13: { ra: 250.42, dec: 36.46, tol: 0.05 },
    };
    for (const [id, g] of Object.entries(golden)) {
      const o = MESSIER.find((x) => x.id === id);
      expect(o, `${id} missing`).toBeDefined();
      expect(Math.abs(o!.ra - g.ra), `${id} ra`).toBeLessThanOrEqual(g.tol);
      expect(Math.abs(o!.dec - g.dec), `${id} dec`).toBeLessThanOrEqual(g.tol);
    }
  });

  it('places objects in the right constellation', () => {
    const expected: Record<string, string> = {
      M1: 'Tau',
      M13: 'Her',
      M27: 'Vul',
      M31: 'And',
      M42: 'Ori',
      M45: 'Tau',
      M51: 'CVn',
      M104: 'Vir',
    };
    for (const [id, con] of Object.entries(expected)) {
      expect(MESSIER.find((o) => o.id === id)?.con, id).toBe(con);
    }
    for (const o of MESSIER) expect(o.con).toMatch(/^[A-Za-z]{3}$/);
  });

  it('carries names and sizes', () => {
    for (const o of MESSIER) expect(o.name.length).toBeGreaterThan(0);
    expect(MESSIER.find((o) => o.id === 'M45')?.name).toBe('Pleiades');
    expect(MESSIER.find((o) => o.id === 'M31')?.sizeArcmin).toBe(190);
    for (const o of MESSIER) {
      if (o.sizeArcmin !== null) expect(o.sizeArcmin).toBeGreaterThan(0);
    }
  });
});

describe('milky way', () => {
  it('ships all five outline levels', () => {
    expect(MILKY_WAY.map((l) => l.id)).toEqual(['ol1', 'ol2', 'ol3', 'ol4', 'ol5']);
  });

  it('keeps every coordinate in range', () => {
    for (const level of MILKY_WAY) {
      expect(level.polygons.length).toBeGreaterThan(0);
      for (const ring of level.polygons) {
        expect(ring.length).toBeGreaterThanOrEqual(4);
        for (const [ra, dec] of ring) {
          expect(inRaRange(ra), `ra out of range in ${level.id}: ${ra}`).toBe(true);
          expect(inDecRange(dec), `dec out of range in ${level.id}: ${dec}`).toBe(true);
        }
      }
    }
  });

  it('closes every ring explicitly', () => {
    for (const level of MILKY_WAY) {
      for (const ring of level.polygons) {
        expect(ring[ring.length - 1], `unclosed ring in ${level.id}`).toEqual(ring[0]);
      }
    }
  });
});
