// GENERATED by scripts/vendor-catalogs.mjs — do not edit by hand.
// Run `npm run vendor:catalogs` to regenerate.
//
// Sky catalogs vendored from d3-celestial (BSD-3-Clause, (c) 2015 Olaf Frohn).
// All right ascensions are degrees in [0, 360); declinations are degrees in
// [-90, 90]. See CREDITS.md at the repo root.

import starsJson from './stars.json';
import constellationsJson from './constellations.json';
import messierJson from './messier.json';
import milkyWayJson from './milkyway.json';

export interface StarRecord {
  ra: number;
  dec: number;
  mag: number;
  /** B-V colour index; 0.65 when the catalogue has no value. */
  bv: number;
  /** Proper name ("Vega", "Sirius", …) or "" when the star has none. */
  name: string;
  /** Hipparcos number, 0 when unknown. */
  hip: number;
}

export interface ConstellationRecord {
  /** 3-letter IAU abbreviation, e.g. "And". */
  id: string;
  name: string;
  /** Primary label position; the first entry of `labels`. */
  labelRa: number;
  labelDec: number;
  /**
   * Every label position for this constellation. One for all of them except
   * Serpens, whose two halves (Caput and Cauda) sit on opposite sides of
   * Ophiuchus and are labelled separately.
   */
  labels: [number, number][];
  /** Polylines already cut at the RA=0/360 seam. */
  lines: [number, number][][];
}

export type MessierType =
  | 'galaxy'
  | 'open_cluster'
  | 'globular_cluster'
  | 'planetary_nebula'
  | 'diffuse_nebula'
  | 'supernova_remnant'
  | 'other';

export interface MessierRecord {
  id: string;
  name: string;
  type: MessierType;
  ra: number;
  dec: number;
  mag: number | null;
  /** Largest dimension in arcminutes, null when the source size is unparseable. */
  sizeArcmin: number | null;
  /** 3-letter IAU constellation abbreviation. */
  con: string;
}

export interface MilkyWayLevel {
  /** "ol1" (faintest) … "ol5" (brightest). */
  id: string;
  /**
   * Rings to fill. Explicitly closed — the last vertex repeats the first, so a
   * stroked outline joins up too. NOT cut at the RA seam (see CREDITS.md).
   */
  polygons: [number, number][][];
}

type StarTuple = [number, number, number, number, string, number];

/** [ra, dec, mag, bv, name, hip], brightest first. */
export const STAR_TUPLES = starsJson.stars as StarTuple[];

/** Faintest magnitude present in STARS. */
export const STAR_MAG_LIMIT: number = starsJson.maxMag;

/**
 * Every catalogued star, brightest first — a renderer can take a prefix to
 * thin the sky. Expanded once, the first time this module is imported.
 */
export const STARS: StarRecord[] = STAR_TUPLES.map(([ra, dec, mag, bv, name, hip]) => ({
  ra,
  dec,
  mag,
  bv,
  name,
  hip,
}));

export const CONSTELLATIONS: ConstellationRecord[] =
  constellationsJson.constellations as ConstellationRecord[];

export const MESSIER: MessierRecord[] = messierJson.objects as MessierRecord[];

export const MILKY_WAY: MilkyWayLevel[] = milkyWayJson.levels as MilkyWayLevel[];

/** Lookup by Messier id ("M31"). */
export const MESSIER_BY_ID: ReadonlyMap<string, MessierRecord> = new Map(
  MESSIER.map((o) => [o.id, o]),
);

/** Lookup by IAU abbreviation ("And"). */
export const CONSTELLATION_BY_ID: ReadonlyMap<string, ConstellationRecord> = new Map(
  CONSTELLATIONS.map((c) => [c.id, c]),
);
